mediapolis_index:
    path: /
    controller: App\Controller\PageController::index
mediapolis_agence:
    path: /agence
    controller: App\Controller\PageController::agence
mediapolis_equipe:
    path: /equipe
    controller: App\Controller\PageController::equipe
mediapolis_offres_strategique:
    path: /offres-strategique
    controller: App\Controller\PageController::offreStrategique
mediapolis_offre_technologiques:
    path: /offre-technologiques
    controller: App\Controller\PageController::offresTechnologiques
mediapolis_offres_operationnelles:
    path: /offres-operationnelles
    controller: App\Controller\PageController::offresOperationnelles
mediapolis_offres_music_event:
    path: /offres-music-event
    controller: App\Controller\PageController::offresMusicEvent
mediapolis_galerie:
    path: /galerie
    controller: App\Controller\PageController::galerie
mediapolis_news:
    path: /news/{page}
    controller: App\Controller\PageController::news
    defaults:
        page: 1
    requirements:
        page: '\d+'
mediapolis_contact:
    path: /contact
    controller: App\Controller\PageController::contact
mediapolis_recrutements:
    path: /recrutements
    controller: App\Controller\PageController::recrutements


##ADMIN##
## ADMIN

admin_root:
    path: /admin
    controller: App\Controller\SecurityController::index

admin_security_login:
    path: /admin/security/login
    controller: App\Controller\SecurityController::login

admin_security_logout:
    path: /admin/security/logout
    controller: App\Controller\SecurityController::logout

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

admin_mails:
    path: /admin/mails
    controller: App\Controller\AdminController::mailList

admin_mail_info:
    path: /admin/mails/{id}
    controller: App\Controller\AdminController::mailInfo

admin_articles:
    path: /admin/news
    controller: App\Controller\AdminController::articleList

admin_articles_add:
    path: /admin/news/add
    controller: App\Controller\AdminController::articleAdd

admin_article_info:
    path: /admin/news/{id}
    controller: App\Controller\AdminController::articleInfo
    requirements:
        id: '\d+'

admin_article_edit:
    path: /admin/news/{id}/edit
    controller: App\Controller\AdminController::articleEdit

admin_article_delete:
    path: /admin/news/{id}/delete
    controller: App\Controller\AdminController::articleDelete

admin_devis:
    path: /admin/devis
    controller: App\Controller\AdminController::adminDevis